### ISSUE TITLE
OS X 10.6.2 clj woes...

### ISSUE THREAD

**Issue by pygy** [citizen428/ClojureX#8]
Hi, 

I have several problems with the clj script on OS X 10.6.2, I'm not well versed in either bash scripts or the JVM environment, so I don't know exactly what to do to sort things out...

Here are the symptoms.

It only works properly when called with it's full path prefixed. 
/User/.../ClojureX/clj works as intended so far (to launch the REPL or a simple .clj file : (print 5)).

The symlink in /usr/local/bin works fine, but only when I run it from the ClojureX directory. When I do that, I get a readlink error message (illegal option -- f, which doesn't make sense), but it works fine otherwise in the scenarios described above, even when you pass a symlink as an argument.

When I try to run "clj" from anywhere else, I get the following:

readlink: illegal option -- f
usage: readlink [-n] [file ...]
Exception in thread "main" java.lang.NoClassDefFoundError: jline/ConsoleRunner
Caused by: java.lang.ClassNotFoundException: jline.ConsoleRunner
        at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:315)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:330)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:250)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:398)

I get a similar message when I try to launch a script directly (shebang: #! /usr/bin/env clj)...

**Comment by citizen428** [comment]
True, I noticed the same yesterday evening at home, it's related to the change I commited yesterday. Unfortunately readlink on OS X is not the same as on Linux, so you get the error message.

**Comment by citizen428** [comment]
I removed the -f option for the time being. Will have to implement some platform neutral way to determine the canonical path.

**Comment by pygy** [comment]
Can this be closed? The project looks dormant, and I'm trying to prune my issues backlog.

**Comment by citizen428** [comment]
Yes, I haven't worked on this in a  long time.
